Feature/2020 11 12 typescript in a serverless backend with NestJS and Azure Functions
ordina-jworks/ordina-jworks.github.io pull request #640
Opened 2020-11-10 00:19 UTC by jasperrosiers

### Thank you for your contribution! Please go through this small checklist to prepare your pull request to be reviewed as soon as possible :)
* [ ] All authors were added to `_data/authors.yml` with a picture and an up-to-date bio
* [ ] The blog post image is of ratio 500x293
  * Feel free to leave a comment if you don't know how to resize your image and someone will gladly help you out
* [ ] The [**one sentence per line** method](https://raw.githubusercontent.com/brandon-rhodes/blog/master/texts/brandon/2012/one-sentence-per-line.rst) has been adopted
* [ ] A spell check has been done
* [ ] All links open in a new tab
  * Example: `[Amazing tech blog](https://ordina-jworks.github.io){:target="_blank" rel="noopener noreferrer"}`
* [ ] The post's content properly resizes according to the window's size
  * Tip: Just shorten your window's horizontal length to easily test this
  * To have images properly resize use `class="image fit"`
  * To have YouTube videos properly resize, wrap the iframe into a `<div class="responsive-video">`
* [ ] If a table of content is: check whether all links are working correctly

### Any specific remarks for the reviewers or anything you need help with?
\<enter text here>

### Checklist for the reviewers before merging
* [ ] Publishing date of the post has been correctly set
  * This can be done by renaming the filename or by setting the date in the header section of the post

2020-11-10 21:04 UTC, DuncanCasteleyn approved these changes
Looking good 🎉

2020-11-10 22:09 UTC, yannickdeturck requested changes
Looks good, @jasperrosiers ! Reads pretty fluently. 👌🏼
I've added a couple of suggestions to polish the post a bit further.

2020-11-10 22:09 UTC, yannickdeturck commented on _posts/2020-11-12-Typescript-in-a-serverless-backend-with-NestJS-and-Azure-Functions.md
> +- customise which Http code you want to return on successful calls, as I did with the `createParameters` method.
I'd write it as HTTP to be consistent with the other usages throughout the blogpost.
```suggestion
- Customise which HTTP code you want to return on successful calls, as I did with the `createParameters` method.
```

2020-11-10 22:09 UTC, yannickdeturck commented on _posts/2020-11-12-Typescript-in-a-serverless-backend-with-NestJS-and-Azure-Functions.md
> +Other setups, like OAuth, Cognito or jwt tokens are also possible.
```suggestion
Other setups, like OAuth, Cognito or JWT tokens are also possible.
```

2020-11-10 22:09 UTC, yannickdeturck commented on _posts/2020-11-12-Typescript-in-a-serverless-backend-with-NestJS-and-Azure-Functions.md
> +For more information on NestJS and its features, check out the very thorough [documentation](https://docs.nestjs.com/){:target="_blank" rel="noopener noreferrer"}
Missing a period at the end. :-)
```suggestion
For more information on NestJS and its features, check out the very thorough [documentation](https://docs.nestjs.com/){:target="_blank" rel="noopener noreferrer"}.
```

2020-11-10 22:09 UTC, yannickdeturck commented on _posts/2020-11-12-Typescript-in-a-serverless-backend-with-NestJS-and-Azure-Functions.md
> +- [The body parameters project](https://github.com/jasperrosiers/body-parameter-tracker){:target="_blank" rel="noopener noreferrer"}
Feel free to include your GitHub project again here. 👍🏼

2020-11-12 11:23 UTC, yannickdeturck approved these changes
Solid work, @jasperrosiers. 👌🏼
Off it goes! 🚀

2020-11-12 11:23 UTC, merged