Feature/2020 11 20 chaos engineering
ordina-jworks/ordina-jworks.github.io pull request #646
Opened 2020-11-24 15:26 UTC by Timverte

### Thank you for your contribution! Please go through this small checklist to prepare your pull request to be reviewed as soon as possible :)
* [ ] All authors were added to `_data/authors.yml` with a picture and an up-to-date bio
* [ ] The blog post image is of ratio 500x293
  * Feel free to leave a comment if you don't know how to resize your image and someone will gladly help you out
* [ ] The [**one sentence per line** method](https://raw.githubusercontent.com/brandon-rhodes/blog/master/texts/brandon/2012/one-sentence-per-line.rst) has been adopted
* [ ] A spell check has been done
* [ ] All links open in a new tab
  * Example: `[Amazing tech blog](https://ordina-jworks.github.io){:target="_blank" rel="noopener noreferrer"}`
* [ ] The post's content properly resizes according to the window's size
  * Tip: Just shorten your window's horizontal length to easily test this
  * To have images properly resize use `class="image fit"`
  * To have YouTube videos properly resize, wrap the iframe into a `<div class="responsive-video">`
* [ ] If a table of content is: check whether all links are working correctly

### Any specific remarks for the reviewers or anything you need help with?
\<enter text here>

### Checklist for the reviewers before merging
* [ ] Publishing date of the post has been correctly set
  * This can be done by renaming the filename or by setting the date in the header section of the post

2020-12-04 17:17 UTC, peterdekinder commented
Twee opmerkingen:
* de table of contents is wel heel uitgebreid. Misschien een aantal chapters omvormen naar bold text of zoiets?
*  de externals links getiteld "Chaos Engineering post" linken beide naar hetzelfde artikel (via een redirect)

2020-12-04 19:37 UTC, KevinVHoutte requested changes

2020-12-04 19:37 UTC, KevinVHoutte commented on _posts/2020-11-20-chaos-engineering.md
> +Or consider an organization that uses a messaging app such as Slack or HipChat to communicate during an incident.
```suggestion
Consider an organization that uses a messaging app such as Slack or HipChat to communicate during an incident.
```

2020-12-04 19:37 UTC, KevinVHoutte commented on _posts/2020-11-20-chaos-engineering.md
> +you will want to inform members of your organization about what you're doing, why you're doing it and when.
```suggestion
you want to inform members of your organization about what you're doing, why you're doing it, and when.
```

2020-12-04 19:37 UTC, KevinVHoutte commented on _posts/2020-11-20-chaos-engineering.md
> +He or She will generally start with something simple like the loss of capacity or the loss of connectivity.
```suggestion
He or she will generally start with something simple like the loss of capacity or the loss of connectivity.
```

2020-12-04 19:37 UTC, KevinVHoutte commented on _posts/2020-11-20-chaos-engineering.md
> +LitmusChaos Litmus is a toolset to do cloud-native chaos engineering.
```suggestion
LitmusChaos is a toolset to do cloud-native chaos engineering.
```

2020-12-04 19:37 UTC, KevinVHoutte commented on _posts/2020-11-20-chaos-engineering.md
> +tags: [Chaos Engineering, DevOps, Chaos, Backend, Netflix, Simian Army]
add resiliency

2020-12-04 19:37 UTC, KevinVHoutte commented on _posts/2020-11-20-chaos-engineering.md
> +title: 'Chaos Engineering'
```suggestion
title: 'Introduction into the world of Chaos Engineering'
```

2020-12-14 15:40 UTC, KevinVHoutte approved these changes

2020-12-14 15:41 UTC, merged