Feature/2021 05 27 chatbot immo
ordina-jworks/ordina-jworks.github.io pull request #667
Opened 2021-05-28 12:08 UTC by IebeMaes

### Thank you for your contribution! Please go through this small checklist to prepare your pull request to be reviewed as soon as possible :)
* [x] All authors were added to `_data/authors.yml` with a picture and an up-to-date bio
* [x] The blog post image is of ratio 500x293
  * Feel free to leave a comment if you don't know how to resize your image and someone will gladly help you out
* [x] The [**one sentence per line** method](https://raw.githubusercontent.com/brandon-rhodes/blog/master/texts/brandon/2012/one-sentence-per-line.rst) has been adopted
* [x] A spell check has been done
* [x] All links open in a new tab
  * Example: `[Amazing tech blog](https://ordina-jworks.github.io){:target="_blank" rel="noopener noreferrer"}`
* [x] The post's content properly resizes according to the window's size
  * Tip: Just shorten your window's horizontal length to easily test this
  * To have images properly resize use `class="image fit"`
  * To have YouTube videos properly resize, wrap the iframe into a `<div class="responsive-video">`
* [x] If a table of content is: check whether all links are working correctly

### Any specific remarks for the reviewers or anything you need help with?
\<enter text here>

### Checklist for the reviewers before merging
* [ ] Publishing date of the post has been correctly set
  * This can be done by renaming the filename or by setting the date in the header section of the post

2021-06-04 09:57 UTC, yannickdeturck requested changes
A very nice blogpost, @IebeMaes !
No real remarks regarding the content. It looks very good.
We can polish the blogpost quite a bit, to make it even better. See my suggestions.

Also, please set yourself as the author of the post. As it is you that has written it. :)
You will need to add yourself in `_data/authors.yml`.

2021-06-04 09:57 UTC, yannickdeturck commented on _posts/2021-05-27-Chatbot-Immo.md
> +```Java
```suggestion
```java
```

2021-06-04 09:57 UTC, yannickdeturck commented on _posts/2021-05-27-Chatbot-Immo.md
> +    System.out.println("cal authorizationUrl->" + authorizationUrl);
It is better to use a logger here. :)

2021-06-04 09:57 UTC, yannickdeturck commented on _posts/2021-05-27-Chatbot-Immo.md
> +        System.out.println("My:" + eventList.getItems());
Logger should also be used here.

2021-06-04 09:57 UTC, yannickdeturck commented on _posts/2021-05-27-Chatbot-Immo.md
> +    System.out.println("cal message:" + message);
And here too.

2021-06-04 09:57 UTC, yannickdeturck commented on _posts/2021-05-27-Chatbot-Immo.md
> +When I got those tokens from the server, I saved the refresh token in the application.properties file so I could use it later to get new access tokens.
You can use backticks for inline code styling. Or to refer to files.
```suggestion
When I got those tokens from the server, I saved the refresh token in the `application.properties` file so I could use it later to get new access tokens.
```

2021-06-04 09:57 UTC, yannickdeturck commented on _posts/2021-05-27-Chatbot-Immo.md
> +When I got those tokens from the server, I saved the refresh token in the application.properties file so I could use it later to get new access tokens.
I don't really understand these part.
The `application.properties` file contains the config for the application. How is something being saved to it at runtime?

2021-06-04 09:57 UTC, yannickdeturck commented on _posts/2021-05-27-Chatbot-Immo.md
> +As a test there is also some code to get the events between two dates, to make sure that I have access to the Google calendar API with the acquired access token.
```suggestion
As a test, there is also some code to get the events between two dates, to make sure that I have access to the Google calendar API with the acquired access token.
```

2021-06-04 09:57 UTC, yannickdeturck commented on _posts/2021-05-27-Chatbot-Immo.md
> +We then get a response with a new access token which we can use to send request to the API.
```suggestion
We then get a response with a new access token which we can use to send the request to the API.
```

2021-06-04 09:57 UTC, yannickdeturck commented on _posts/2021-05-27-Chatbot-Immo.md
> +Because we need the free meeting times off the user, we would need the freebusy schedule.
```suggestion
Because we need the free meeting times of the user, we would need the freebusy schedule. 
```

2021-06-04 09:57 UTC, yannickdeturck commented on _posts/2021-05-27-Chatbot-Immo.md
> +```Java
```suggestion
```java
```

2021-06-04 09:57 UTC, yannickdeturck commented on _posts/2021-05-27-Chatbot-Immo.md
> +I wanted the timeslots to appear in the chatbot as quick reply’s.
```suggestion
I wanted the timeslots to appear in the chatbot as quick replies. 
```

2021-06-04 09:57 UTC, yannickdeturck commented on _posts/2021-05-27-Chatbot-Immo.md
> +When I had the correct structure I could send these quick reply’s back to Chatlayer with a simple POST request.
```suggestion
When I had the correct structure, I could send these quick replies back to Chatlayer with a simple POST request.
```

2021-06-04 09:57 UTC, yannickdeturck commented on _posts/2021-05-27-Chatbot-Immo.md
> +```Java
```suggestion
```java
```

2021-06-04 09:57 UTC, yannickdeturck commented on _posts/2021-05-27-Chatbot-Immo.md
> +```Java
```suggestion
```java
```

2021-06-04 09:57 UTC, yannickdeturck commented on _posts/2021-05-27-Chatbot-Immo.md
> +[Have a look at the demo!](https://www.youtube.com/watch?v=qWsC7zrawBA){:target="_blank" rel="noopener noreferrer"}
Nice! 👍🏼

2021-06-04 09:57 UTC, yannickdeturck commented on _posts/2021-05-27-Chatbot-Immo.md
> +      * Have ability to affect the public debate and our perception of right and wrong
```suggestion
      * Can affect the public debate and our perception of right and wrong
```

2021-06-04 09:57 UTC, yannickdeturck commented on _posts/2021-05-27-Chatbot-Immo.md
> +  * Companies are so successful because they have such a large amount of data, not because of there innovations
```suggestion
  * Companies are so successful because they have such a large amount of data, not because of their innovations
```

2021-06-04 09:57 UTC, yannickdeturck commented on _posts/2021-05-27-Chatbot-Immo.md
> +  * Because of these couple big companies its difficult for new companies to innovate because they don’t have the data for it
```suggestion
  * Because of these couple big companies, it is difficult for new companies to innovate because they don’t have the data for it
```

2021-06-04 09:57 UTC, yannickdeturck commented on _posts/2021-05-27-Chatbot-Immo.md
> +      * ..
```suggestion
      * ...
```

2021-06-04 09:57 UTC, yannickdeturck commented on _posts/2021-05-27-Chatbot-Immo.md
> +* Right now you can get your pod from a pod provider or you could host your pod yourself.
Remove period for consistency.
```suggestion
* Right now you can get your pod from a pod provider or you could host your pod yourself
```

2021-06-04 09:57 UTC, yannickdeturck commented on _posts/2021-05-27-Chatbot-Immo.md
> +I used the Docker container to setup my solid server.
```suggestion
I used the Docker container to setup my Solid server. 
```

2021-06-04 09:57 UTC, yannickdeturck commented on _posts/2021-05-27-Chatbot-Immo.md
> +If we navigate to localhost:8443, we visit the homepage off the Solid server.
```suggestion
If we navigate to `localhost:8443`, we visit the homepage of the Solid server. 
```

2021-06-04 09:57 UTC, yannickdeturck commented on _posts/2021-05-27-Chatbot-Immo.md
> +First we get the message that the page is not secure but when clicking through we arrive at the page where we can register a new account or login to an existing one.
```suggestion
First we get the message that the page is not secure but when clicking through, we arrive at the page where we can register a new account or login to an existing one.
```

2021-06-04 09:57 UTC, yannickdeturck commented on _posts/2021-05-27-Chatbot-Immo.md
> +```
```suggestion
```json
```

2021-06-04 09:57 UTC, yannickdeturck commented on _posts/2021-05-27-Chatbot-Immo.md
> +I think the most important one here is whether or not you want your server to be able to host more then one pod or not.
```suggestion
I think the most important one here is whether or not you want your server to be able to host more than one pod or not. 
```

2021-06-04 09:57 UTC, yannickdeturck commented on _posts/2021-05-27-Chatbot-Immo.md
> +For testing purposes I set the multiuser setting to ‘true’ so my server is capable off hosting multiple pods.
```suggestion
For testing purposes, I set the multiuser setting to `true` so my server is capable of hosting multiple pods.
```

2021-06-04 09:57 UTC, yannickdeturck commented on _posts/2021-05-27-Chatbot-Immo.md
> +As you can see below, when creating an account, your webId (unique identifier for Solid pods) is made off your username and the domain (in this case is this localhost:8443).
```suggestion
As you can see below, when creating an account, your webId (unique identifier for Solid pods) is made of your username and the domain (in this case this is `localhost:8443`). 
```

2021-06-04 09:57 UTC, yannickdeturck commented on _posts/2021-05-27-Chatbot-Immo.md
> +The ‘/profile/card#me’ is just to specify where your profile information is stored.
```suggestion
The `/profile/card#me` is just to specify where your profile information is stored. 
```

2021-06-04 09:57 UTC, yannickdeturck commented on _posts/2021-05-27-Chatbot-Immo.md
> +When registering a new account you need to add an entry for it in you local hosts file like this:
```suggestion
When registering a new account you need to add an entry for it in you local `hosts` file like this: 
```

2021-06-04 09:57 UTC, yannickdeturck commented on _posts/2021-05-27-Chatbot-Immo.md
> +In this overview you could also revoke access and update the kind off access that these applications have.
```suggestion
In this overview you could also revoke access and update the kind of access that these applications have.
```

2021-06-04 09:57 UTC, yannickdeturck commented on _posts/2021-05-27-Chatbot-Immo.md
> +As mentioned before you can store any kind of data on your pod, this goes from .txt files, to .html files and even .ttl files.
```suggestion
As mentioned before, you can store any kind of data on your pod, this goes from `.txt` files, to `.html` files and even `.ttl` files. 
```

2021-06-04 09:57 UTC, yannickdeturck commented on _posts/2021-05-27-Chatbot-Immo.md
> +Before we can discuss turtle we need to have a basic understanding off RDF and linked data.
```suggestion
Before we can discuss Turtle we need to have a basic understanding of RDF and linked data. 
```

2021-06-04 09:57 UTC, yannickdeturck commented on _posts/2021-05-27-Chatbot-Immo.md
> +Next to N-Triples, JSON-LD and RDF/XML it is one off the four common formats to write RDF.
```suggestion
Next to N-Triples, JSON-LD and RDF/XML it is one of the four common formats to write RDF. 
```

2021-06-04 09:57 UTC, yannickdeturck commented on _posts/2021-05-27-Chatbot-Immo.md
> +In turtle you can declare prefixes to use as a shortcut throughout the rest of the file so you don’t have to write full URI’s everywhere.
```suggestion
In Turtle you can declare prefixes to use as a shortcut throughout the rest of the file so you don’t have to write full URI’s everywhere. 
```

2021-06-04 09:57 UTC, yannickdeturck commented on _posts/2021-05-27-Chatbot-Immo.md
> +Because of the short notation Turtle is much easier to understand then the other formats.
```suggestion
Because of the short notation, Turtle is much easier to understand than the other formats.
```

2021-06-04 09:57 UTC, yannickdeturck commented on _posts/2021-05-27-Chatbot-Immo.md
> +The first step in to get information your solid pod is authentication.
```suggestion
The first step to get information in your solid pod is authentication. 
```

2021-06-04 09:57 UTC, yannickdeturck commented on _posts/2021-05-27-Chatbot-Immo.md
> +The loggedIn and loggedOut component do exactly what you expect them to do, show some content when the user is logged in and show other content when the user isn’t logged in.
```suggestion
The `loggedIn` and `loggedOut` component do exactly what you expect them to do, show some content when the user is logged in and show other content when the user isn’t logged in. 
```

2021-06-04 09:57 UTC, yannickdeturck commented on _posts/2021-05-27-Chatbot-Immo.md
> +Then we have the loginButton component which shows popup.html which is the popup screen you see in the login section above.
```suggestion
Then we have the `loginButton` component which shows `popup.html` which is the popup screen you see in the login section above. 
```

2021-06-04 09:57 UTC, yannickdeturck commented on _posts/2021-05-27-Chatbot-Immo.md
> +```
```suggestion
```typescript
```

2021-06-04 09:57 UTC, yannickdeturck commented on _posts/2021-05-27-Chatbot-Immo.md
> +```
```suggestion
```typescript
```

2021-06-04 09:57 UTC, yannickdeturck commented on _posts/2021-05-27-Chatbot-Immo.md
> +Then we would need de data object.
```suggestion
Then we would need the data object.
```

2021-06-04 09:57 UTC, yannickdeturck commented on _posts/2021-05-27-Chatbot-Immo.md
> +And with the data object and the webId we can get the profile, once we have this object you can ask for anything you see in the structure off the profile card under :me.
```suggestion
And with the data object and the webId, we can get the profile.
Once we have this object you can ask for anything you see in the structure off the profile card under `:me`. 
```

2021-06-04 09:57 UTC, yannickdeturck commented on _posts/2021-05-27-Chatbot-Immo.md
> +The profile object we would get would actually be the #me part off the card.
```suggestion
The profile object we would get would actually be the `#me` part of the card. 
```

2021-06-04 09:57 UTC, yannickdeturck commented on _posts/2021-05-27-Chatbot-Immo.md
> +```
```suggestion
```typescript
```

2021-06-04 09:57 UTC, yannickdeturck commented on _posts/2021-05-27-Chatbot-Immo.md
> +```
```suggestion
```typescript
```

2021-06-04 09:57 UTC, yannickdeturck commented on _posts/2021-05-27-Chatbot-Immo.md
> +```
```suggestion
```typescript
```

2021-06-04 09:57 UTC, yannickdeturck commented on _posts/2021-05-27-Chatbot-Immo.md
> +To get the full name we place the predicate between [ ] after the profile object.
```suggestion
To get the full name, we place the predicate between `[ ]` after the profile object.
```

2021-06-04 09:57 UTC, yannickdeturck commented on _posts/2021-05-27-Chatbot-Immo.md
> +You can also see that for example the address isn’t stored under the :me part but has an id.
```suggestion
You can also see that for example the address isn’t stored under the `:me` part but it has an id. 
```

2021-06-04 09:57 UTC, yannickdeturck commented on _posts/2021-05-27-Chatbot-Immo.md
> +To get the properties off the address we would have to do something like this:
```suggestion
To get the properties of the address we would have to do something like this:
```

2021-06-04 09:57 UTC, yannickdeturck commented on _posts/2021-05-27-Chatbot-Immo.md
> +First off all, I want to thank Ordina for the chance that they have given me to do this internship.
```suggestion
First of all, I want to thank Ordina for the chance that they have given me to do this internship. 
```

2021-06-04 09:57 UTC, yannickdeturck commented on _posts/2021-05-27-Chatbot-Immo.md
> +They always provided me with feedback when I finished a part off the solution and would always make time to help me with my questions or to explain things that weren’t clear.
```suggestion
They always provided me with feedback when I finished a part of the solution and would always make time to help me with my questions or to explain things that weren’t clear. 
```

2022-03-09 12:58 UTC, DenMette approved these changes

2022-03-09 12:58 UTC, merged