Feature/aws summit 2023
ordina-jworks/ordina-jworks.github.io pull request #792
Opened 2023-06-26 15:22 UTC by yolanv

### Thank you for your contribution! Please go through this small checklist to prepare your pull request to be reviewed as soon as possible :)
* [X] All authors were added to `_data/authors.yml` with a picture and an up-to-date bio
* [X] The blog post image is of ratio 500x293
  * Feel free to leave a comment if you don't know how to resize your image and someone will gladly help you out
* [X] The [**one sentence per line** method](https://raw.githubusercontent.com/brandon-rhodes/blog/master/texts/brandon/2012/one-sentence-per-line.rst) has been adopted
* [X] A spell check has been done
* [X] All links open in a new tab
  * Example: `[Amazing tech blog](https://ordina-jworks.github.io){:target="_blank" rel="noopener noreferrer"}`
* [X] The post's content properly resizes according to the window's size
  * Tip: Just shorten your window's horizontal length to easily test this
  * To have images properly resize use `class="image fit"`
  * To have YouTube videos properly resize, wrap the iframe into a `<div class="responsive-video">`
* [X] If a table of content is: check whether all links are working correctly

### Any specific remarks for the reviewers or anything you need help with?
\<enter text here>

### Checklist for the reviewers before merging
* [ ] Publishing date of the post has been correctly set
  * This can be done by renaming the filename or by setting the date in the header section of the post

2023-06-26 19:59 UTC, pietervincken requested changes

2023-06-26 19:59 UTC, pietervincken commented on _posts/2023-06-20-aws-summit-amsterdam-2023.md
> +With these kinds of topics, users are always afraid of their data and the privacy that surrounds the whole concept.
```suggestion
With these kinds of topics, privacy is often a concern.
Users want to know how their data is used and what measures are taken to keep it safe.
```

2023-06-26 19:59 UTC, pietervincken commented on _posts/2023-06-20-aws-summit-amsterdam-2023.md
> +They always design their newest features and services with privacy on the first place, and they will to continue to invest in ways to ensure that they live up to their own standards.
```suggestion
They always design their newest features and services with privacy as a primary concern, and they will to continue to invest in ways to ensure that they live up to their own standards.
```

2023-06-26 19:59 UTC, pietervincken commented on _posts/2023-06-20-aws-summit-amsterdam-2023.md
> +The speaker spoke of companies that had successfully migrated their infrastructure to the cloud.
```suggestion
They spoke of companies that had successfully migrated their infrastructure to the cloud.
```

2023-06-26 19:59 UTC, pietervincken commented on _posts/2023-06-20-aws-summit-amsterdam-2023.md
> +There were a few companies that were there to share their experience.
```suggestion
Some of these companies shared their experience on stage.
```

2023-06-26 19:59 UTC, pietervincken commented on _posts/2023-06-20-aws-summit-amsterdam-2023.md
> +They added a functionality to their application where they estimate how occupied the park was at the current moment.
```suggestion
They added a functionality to their application where they estimate how occupied the park at any point in time.
```

2023-06-26 19:59 UTC, pietervincken commented on _posts/2023-06-20-aws-summit-amsterdam-2023.md
> +Other companies were HEMA, PostNL, Epic Games, which were presented by Andy and how these companies used the newest services and features.
Name some services here?

2023-06-26 19:59 UTC, pietervincken commented on _posts/2023-06-20-aws-summit-amsterdam-2023.md
> +Takeaway (Just Eat) also gave a small presentation on how they use AWS to improve customer experience in their app.
Again, name 1 or 2 services and how it improved their situation.

2023-06-29 20:17 UTC, DuncanCasteleyn approved these changes
Nice post

2023-06-30 09:00 UTC, pietervincken approved these changes

2023-06-30 10:57 UTC, merged