Feature: AWS Cognito + Azure AD
ordina-jworks/ordina-jworks.github.io pull request #801
Opened 2023-08-30 15:17 UTC by yolanv

### Thank you for your contribution! Please go through this small checklist to prepare your pull request to be reviewed as soon as possible :)
* [X] All authors were added to `_data/authors.yml` with a picture and an up-to-date bio
* [X] The blog post image is of ratio 500x293
  * Feel free to leave a comment if you don't know how to resize your image and someone will gladly help you out
* [X] The [**one sentence per line** method](https://raw.githubusercontent.com/brandon-rhodes/blog/master/texts/brandon/2012/one-sentence-per-line.rst) has been adopted
* [X] A spell check has been done
* [X] All links open in a new tab
  * Example: `[Amazing tech blog](https://ordina-jworks.github.io){:target="_blank" rel="noopener noreferrer"}`
* [X] The post's content properly resizes according to the window's size
  * Tip: Just shorten your window's horizontal length to easily test this
  * To have images properly resize use `class="image fit"`
  * To have YouTube videos properly resize, wrap the iframe into a `<div class="responsive-video">`
* [X] If a table of content is: check whether all links are working correctly

### Any specific remarks for the reviewers or anything you need help with?
\<enter text here>

### Checklist for the reviewers before merging
* [ ] Publishing date of the post has been correctly set
  * This can be done by renaming the filename or by setting the date in the header section of the post

2023-08-30 15:23 UTC, yolanv commented
Ready for review :)
@BikersDelight @pietervincken @DenMette

2023-09-07 15:58 UTC, pietervincken requested changes

2023-09-07 15:58 UTC, pietervincken commented on _posts/2023-09-18-aws-cognito-azure-ad.md
> +But what happens when you're already invested in Azure Active Directory as your primary identity provider?
Add that many companies already rely on office 365 and therefor have Azure AD setup (or have legacy on premise)

2023-09-07 15:58 UTC, pietervincken commented on _posts/2023-09-18-aws-cognito-azure-ad.md
> +While many companies utilize Azure AD, they may not fully adopt the entire Azure ecosystem.
Maybe make the O365 link here.

2023-09-07 15:58 UTC, pietervincken commented on _posts/2023-09-18-aws-cognito-azure-ad.md
> +However, based on our experience, integrating Cognito with AWS services offers a cleaner solution, especially if your application operates on AWS.
Rephrase to flow better. 

Implementing Single Sign-On is a security best-practice, highlight why (easy on-off boarding, central management, easy policy enforcement, ...). 

SSO in many organisations is done through AD (Azure or on-premise) due to O365. 

Implementing SSO in other places makes a ton of sence.

2023-09-07 15:58 UTC, pietervincken commented on _posts/2023-09-18-aws-cognito-azure-ad.md
> +Can these two seemingly distinct systems work together to provide a unified authentication experience?
Nice teaser 😄

2023-09-07 15:58 UTC, pietervincken commented on _posts/2023-09-18-aws-cognito-azure-ad.md
> +resource "" "user_to_group_lambda_permission" {
Typo? Empty resource type here.

2023-09-07 15:58 UTC, pietervincken commented on _posts/2023-09-18-aws-cognito-azure-ad.md
> +By following this approach, we can seamlessly authenticate our enterprise users across AWS services.
In conclusion explain what this has solved compared to alternatives. Integration with other AWS services is a key factor, explain this in more detail. 

Explain what can be improved on the example to make it production ready, if anything. 

Maybe as a final parting thought (optional) add that this is only for allowing applications to authenticate against cognito, it's not to setup SSO for AWS itself.

2023-09-07 15:59 UTC, pietervincken commented
Interesting post and super relevant for me 😄  Got a question about this today in my project. So I will share the post as soon as it's live!

2023-09-13 12:57 UTC, pietervincken approved these changes

2023-09-13 14:17 UTC, yolanv commented
Wilt er iemand nog een review doen of is het oké zo? @DenMette  @BikersDelight

2023-09-13 14:22 UTC, DenMette commented
> Wilt er iemand nog een review doen of is het oké zo? @DenMette @BikersDelight

Voor mij is het goed, dan lanceren we hem binnen 5 dagen.

2023-09-13 14:22 UTC, denmette approved these changes

2023-09-13 14:56 UTC, merged